# Uncomment this line to define a global platform for your project
# Comment this line if you're not using Swift and don't want to use dynamic frameworks
platform :ios, '8.0'

target 'DouYuDemo' do

  use_frameworks!

pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 3.8.1'

end
